name: boonda_mitra
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+14

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  firebase_analytics: ^10.10.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_builder_validators: 
    git:
      url: https://github.com/ferisetyo1/form_builder_validators.git
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  gettext: ^1.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  icons_launcher: ^2.1.7
  image_cropper: ^6.0.0
  image_picker: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  jwt_decode: ^0.3.1
  package_info_plus: any
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^25.1.41+2
  url_launcher: ^6.2.6
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/features/

icons_launcher:
  image_path: "images/ic_boonda.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#F2893C"
  image: images/ic_boonda.jpg

  android_12:
    image: images/ic_boonda.jpg
    icon_background_color: "#F2893C"

  web: true