// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCq_CVy4udGkXg6tAlG9LrY24QhfLlex4',
    appId: '1:165745023871:android:9c1104fa25f5b10ea4d84a',
    messagingSenderId: '165745023871',
    projectId: 'boonda-apps',
    storageBucket: 'boonda-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9S-LgalXQaGY7dN1GJ8vui_E17XR3uBY',
    appId: '1:165745023871:ios:0769b06e27f2c232a4d84a',
    messagingSenderId: '165745023871',
    projectId: 'boonda-apps',
    storageBucket: 'boonda-apps.appspot.com',
    androidClientId: '165745023871-0ukbujnh322fmmfncu1tnu7030b0lfg4.apps.googleusercontent.com',
    iosClientId: '165745023871-b9ahta0vsa7ridgv23le7do7p9cj18n4.apps.googleusercontent.com',
    iosBundleId: 'com.gti.boonda.daycare.dev',
  );
}
